# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/adventure_business',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/adventure_business',
                'lib_path': 'adventure_business'},
  'syms': {'adventure_business.core': {'adventure_business.core.foo': ('core.html#foo', 'adventure_business/core.py')}}}
